### 게시글 조회
GET http://localhost:8031/board/list?boardTypeCode=2&offset=1
Content-Type: application/json
Accept: */*

### 게시글 상세 조회
GET http://localhost:8031/board/list/detail/2
Content-Type: application/json
Accept: */*

### 게시글 등록
POST http://localhost:8031/board/register
Content-Type: application/json
Accept: */*

{
  "title": "신규등록2222",
  "content": "신규글내용2222",
  "viewCount": 5,
  "username": "최사원",
  "userRank": "팀장",
  "teamName": "개발2팀",
  "userCode": 2,
  "boardTypeCode": 1


}

### 게시글 수정
PATCH http://localhost:8031/board/update
Content-Type: application/json
Accept: */*

{
  "boardCode": 3,
  "title": "한 번 더 수정한 제목",
  "content": "한 번 더 수정한 내용"
}

### 게시글 삭제
PATCH http://localhost:8031/board/delete/9
Content-Type: application/json
Accept: */*

### 댓글 조회
GET http://localhost:8031/board/comment/4
Content-Type: application/json
Accept: */*

### 댓글 등록
POST http://localhost:8031/board/comment/register
Content-Type: application/json
Accept: */*

{
  "commentContent": "신규 댓글 내용",
  "boardCode": 2
}

### 댓글 수정
PATCH http://localhost:8031/board/comment/update
Content-Type: application/json
Accept: */*

{
  "commentCode": 3,
  "commentContent": "댓글 수정 테스트222"
}

### 댓글 삭제
PATCH http://localhost:8031/board/comment/delete/5
Content-Type: application/json
Accept: */*

### 관심게시글 조회
GET http://localhost:8031/board/interest/list
Content-Type: application/json
Accept: */*

### 관심게시글 상세 조회
GET http://localhost:8031/board/interest/detail/3
Content-Type: application/json
Accept: */*

### 관심게시글 등록
POST http://localhost:8031/board/interest/register
Content-Type: application/json
Accept: */*

{
  "boardCode": 10,
  "userCode": 21
}

### 관심게시글 삭제
PATCH http://localhost:8031/board/interest/delete
Content-Type: application/json
Accept: */*

{
  "interestCode": 7
}


